#pragma once
#include "ircserver.hpp"

int	err_nosuchnick(int fd, std::string nick);
int	err_nosuchserver(int fd, std::string server);
int	err_nosuchchannel(int fd, std::string channel);
int	err_cannotsendtochan(int fd, std::string chan);
int	err_toomanychannels(int fd, std::string chan);
int	err_wasnosuchnick(int fd, std::string nick);
int	err_toomanytargets(int fd, std::string target, short error_code, std::string abort_msg);
int	err_nosuchservice(int fd, std::string service_name);
int	err_noorigin(int fd);
int	err_norecipient(int fd, std::string command);
int	err_notexttosend(int fd);
int	err_notoplevel(int fd, std::string mask);
int	err_wildtoplevel(int fd, std::string mask);
int	err_badmask(int fd, std::string mask);
int	err_unknowncommand(int fd, std::string command);
int	err_nomotd(int fd);
int	err_noadmininfo(int fd, std::string server);
int	err_fileerror(int fd, std::string file_op, std::string file);
int	err_nonicknamegiven(int fd);
int	err_erroneusnickname(int fd, std::string nick);
int	err_nicknameinuse(int fd, std::string nick);
int	err_nickcollision(int fd, std::string nick, std::string user, std::string host);
int	err_unavailableresource(int fd, std::string resource);
int	err_usernotinchannel(int fd, std::string nick, std::string channel);
int	err_notochannel(int fd, std::string channel);
int	err_useronchannel(int fd, std::string user, std::string channel);
int	err_nologin(int fd, std::string user);
int	err_summondisabled(int fd);
int	err_userdisabled(int fd);
int	err_notregistered(int fd);
int	err_needmoreparams(int fd, std::string command);
int	err_alreadyregistered(int fd);
int	err_nopermforhost(int fd);
int	err_passwdmismatch(int fd);
int	err_yourebannedcreep(int fd);
int	err_youwillbebanned(int fd);
int	err_keyset(int fd, std::string channel);
int	err_channelisfull(int fd, std::string channel);
int	err_unknownmode(int fd, char mode, std::string channel);
int	err_inviteonlychan(int fd, std::string channel);
int	err_bannedfromchan(int fd, std::string channel);
int	err_badchannelkey(int fd, std::string channel);
int	err_badchanmask(int fd, std::string channel);
int	err_nochanmodes(int fd, std::string channel);
int	err_banlistfull(int fd, char stuff, std::string channel);
int	err_noprivileges(int fd);
int	err_chanoprivsneeded(int fd, std::string channel);
int	err_cantkillserver(int fd);
int	err_restricted(int fd);
int	err_uniqoprivsneeded(int fd);
int	err_nooperhost(int fd);
int	err_umodeunknownflag(int fd);
int	err_usersdontmatch(int fd);